Featured Branch Merge to Apple Clone
AhmedAmin90/Apple-clone pull request #1
Opened 2020-10-29 21:24 UTC by MrkarlosM

Pull request for merging:

- Gradient background for divs.
- Background images.
- The main body.
- The footer part of the contact data of the company.
- Footer part for other links.

2020-10-29 22:54 UTC, ebeagusamuel requested changes
# Changes Required :recycle: 
#### Hi team :wave: 
You have done well with this project, but there are some issues that you will need to fix and I will be pointed them out below. 
## Changes to implement :writing_hand: 
- [x] Your README is OK but can be even better. You can provide more description of the project and can even put the link to the original project so anyone looking at the project will be able to access the page you cloned.
- [x] The PR title is not meaningful. Use a more meaningful PR title that provides more context about what the PR is about.
- [ ] This is currently how your website looks like when I visit the link to the live project:
![Screenshot from 2020-10-29 23-43-01](https://user-images.githubusercontent.com/57847212/97640267-abf32580-1a40-11eb-8a7a-d3583667966f.png)
This is happening because of the way you specify the path to your images in your CSS. Currently, you are specifying the path like this `/src/images/your_verse_title_small.png` which will work normally in your local development environment but won't work in a production environment which is what s happening now. You should specify the path like this `../images/your_verse_hero.jpg`.

Please fix all the changes highlighted and when you are done, request for another review.
slack(@ebeagusamuel)

2020-10-29 22:54 UTC, ebeagusamuel commented on index.html
> +            <div class="product-four">&nbsp;</div>
- [ ] It contains four elements which are links (to other articles or #). The four elements at the bottom of the page(i.e the products) should be links(`<a href="#">`)

2020-10-29 23:50 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @MrkarlosM and @AhmedAmin90 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [x] Please provide more description of the project as previous TSE suggested.
- [ ] I tested your project on my local machine it is working well. Please update your live link

### Footer
- [ ] Please fix the flag image issue in footer as prious TSE explained.

|[Source Page](https://web.archive.org/web/20140301004610/http://www.apple.com/)|[Clone Page](https://raw.githack.com/AhmedAmin90/Apple-clone/featured/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/97643989-effb2000-1a6a-11eb-9868-4a7f8ade77f1.png)|![clone](https://user-images.githubusercontent.com/29689273/97643990-f1c4e380-1a6a-11eb-9985-00967aca18dc.png)|


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-30 00:32 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @MrkarlosM and @AhmedAmin90 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly compare the screenshots below 👇 and work on the suggested change.

### Footer
- [ ] Please fix the flag image issue in the footer as previous TSE explained.

|[Source Page](https://web.archive.org/web/20140301004610/http://www.apple.com/)|[Clone Page](https://raw.githack.com/AhmedAmin90/Apple-clone/featured/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/97643989-effb2000-1a6a-11eb-9868-4a7f8ade77f1.png)|![clone](https://user-images.githubusercontent.com/29689273/97643990-f1c4e380-1a6a-11eb-9985-00967aca18dc.png)|


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-30 00:32 UTC, umairarshadbutt commented on index.html
> +                    <li><a href="#"> <img class="usa-flag" src="../images/image-(1).png" alt="flag" height="16" width="16"> </a></li>
The correct path is `src="./src/images/image-(1).png"`

2020-10-30 01:16 UTC, abredi approved these changes
### Status: Approved 🙌 🎇
Hi @MrkarlosM and @AhmedAmin90, Congratulations 🎊 👏, you did very well on this project. Kindly check and fix the following inline code review comment for enhancement.

Now, you can merge the PR to master and move ahead.
Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/)

2020-10-30 01:16 UTC, abredi commented on index.html
> +                        </form> <input type="text"> <i class="fas fa-search"></i></div>
Kindly move the input field into the form.

2020-10-30 14:41 UTC, merged